import { canDouble, canSplit, createShoe, cutCardRemaining, dealInitialRound, dealerShouldHit, handTotal, settleHand, settleInsurance, shouldReshuffle, shoePenetration } from '../lib/game.ts';
import type { GameHand } from '../lib/game.ts';
import { DEFAULT_TABLE_RULES } from '../lib/rules.ts';
import { estimatedPlayerEdge, hiLoValue, trueCount } from '../lib/counting.ts';
import { estimateHitStandOdds } from '../lib/odds.ts';
let cardId = 0;
const c = (rank: any) => ({ rank, suit: '♠' as const, id: `${rank}-${cardId++}` });
const hand = (cards: any[], bet = 10): GameHand => ({ id: 'h', cards: cards.map(c), bet, doubled: false, surrendered: false, splitAces: false, fromSplit: false });
function ok(value: boolean, name: string) { if (!value) throw new Error(`Failed: ${name}`); }
ok(handTotal([c('A'),c('6')]).total === 17 && handTotal([c('A'),c('6')]).soft, 'soft ace totals');
ok(!dealerShouldHit([c('A'),c('6')], DEFAULT_TABLE_RULES), 'S17 stands');
ok(dealerShouldHit([c('A'),c('6')], { ...DEFAULT_TABLE_RULES, dealerHitsSoft17: true }), 'H17 hits');
ok(settleHand(hand(['A','K']), [c('T'),c('7')]).credit === 25, 'blackjack 3:2');
ok(settleHand({ ...hand(['T','9'], 20), doubled: true }, [c('T'),c('8')]).credit === 40, 'double settlement');
ok(canSplit(hand(['8','8']), DEFAULT_TABLE_RULES, 1) && canDouble({ ...hand(['5','4']), fromSplit: true }, DEFAULT_TABLE_RULES), 'split and DAS');
ok(!canSplit(hand(['8']), DEFAULT_TABLE_RULES, 1), 'incomplete dealt hand cannot split');
ok(createShoe(6).length === 312 && createShoe(1).length === 52, 'shoe counts');
ok(settleInsurance(5, true).credit === 15 && settleInsurance(5, true).net === 10, 'insurance pays 2:1');
ok(settleInsurance(5, false).credit === 0 && settleInsurance(5, false).net === -5, 'losing insurance stake');
const ordered = dealInitialRound(createShoe(1), [5, 0, 25], () => 'x');
ok(ordered.hands.length === 2 && ordered.events.map(e => e.kind === 'player' ? e.spot : 'D').join(',') === '1,3,D,1,3,D', 'multi-spot round robin deal order');
ok(ordered.hands.reduce((sum, item) => sum + item.bet, 0) === 30 && settleInsurance(15, true).net === 30, 'aggregate multi-spot insurance');
const simultaneousBlackjacksMainCredit = settleHand(hand(['A','K']), [c('A'),c('T')]).credit;
const simultaneousBlackjacksInsurance = settleInsurance(5, true);
ok(simultaneousBlackjacksMainCredit + simultaneousBlackjacksInsurance.credit - 10 - 5 === 10, 'player and dealer blackjack with insurance');
ok(hiLoValue(c('2')) === 1 && hiLoValue(c('7')) === 0 && hiLoValue(c('A')) === -1, 'Hi-Lo card values');
ok(trueCount(6, 156) === 2, 'true count uses fractional decks remaining');
ok(estimatedPlayerEdge(DEFAULT_TABLE_RULES, 2) > estimatedPlayerEdge(DEFAULT_TABLE_RULES, 0), 'positive true count improves estimated player edge');
ok(DEFAULT_TABLE_RULES.multipleHandsEnabled === true, 'multiple-hand play remains the default');
const oddsShoe = createShoe(1);
const twentyOdds = estimateHitStandOdds([c('T'), c('K')], c('6'), oddsShoe, DEFAULT_TABLE_RULES, 400);
ok(twentyOdds.standWin > twentyOdds.hitWin && twentyOdds.standWin > 50, 'standing on 20 is safer than hitting once');
ok(shoePenetration(1) === .5 && shoePenetration(2) === .65 && shoePenetration(6) === .75, 'deck-size-aware penetration');
ok(cutCardRemaining(1) === 26 && cutCardRemaining(2) === 37 && cutCardRemaining(6) === 78, 'cut-card positions');
ok(shouldReshuffle(26, 1) && !shouldReshuffle(27, 1) && shouldReshuffle(78, 6) && !shouldReshuffle(79, 6), 'reshuffle boundaries');
console.log('Blackjack game validation passed.');